### PR TITLE
Add prompt to select `Database` and `Auth guard`

### PR DESCRIPTION
**Pull request by n0uur**
### 🔗 Linked issue

https://discord.com/channels/423256550564691970/1199775897448882286

### ❓ Type of change

- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

- Add prompt to select `Database Driver` and `Auth Guard` only for `Web Starter Kit` and `API Starter Kit` and if it not specified in CLI arguments.
- Remove default value of `--db` and `--auth-guard` and it will prompt to select instead
- Add a warning message if they select to not install dependencies they will need to configure both guards and db manually

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

PS. Please, excuse my grammar. If there are any typos please notify me, I will fix it asap. :)

### CODE REVIEW

**Comment by thetutlage** [comment]
Can we have tests for the case where user decides to skip the prompts?

**Comment by n0uur** [comment]
Done! I've added those test cases, and add file checking if user is not skipping the prompt.

**Comment by Julien-R44** [comment]
i have some concerns about that PR : why we are not using the `configure` command of `lucid` and `auth` packages? Here it seems to me that we are duplicating exactly the same logic. what we can do is, pass no arguments when you run `node ace configure @adonisjs/lucid` and Lucid will take over and propose the prompts to select the database. Same for auth

otherwise, more generally, it seems to me that we've drifted a little bit from the initial idea we had with `create-adonisjs`

here, we're adding logic specific to `web-starter-kit` and `api-starter-kit` directly in `create-adonisjs`. i don't think this is wanted. the idea was rather to allow the different starter kits to expose a `configure.ts` which would be executed by `create-adonisjs`. i believe this would be much more flexible

imagine tomorrow someone who wants to make their own starter kit and also have a prompt for lucid/auth. I think it will not be possible

**Comment by n0uur** [comment]
> here, we're adding logic specific to web-starter-kit and api-starter-kit directly in create-adonisjs. i don't think this is wanted. the idea was rather to allow the different starter kits to expose a configure.ts which would be executed by create-adonisjs. i believe this would be much more flexible

I completely agree with the approach of allowing different starter kits to expose a `configure.ts`. This would indeed offer more flexibility.

And just to explain, my PR's got a bit of a different angle. I'm all about making things super easy for folks jumping over from other places or just starting out with Adonis. Think of it like this: someone could just run `npm init` and boom. they're on their way without having to dig through a ton of docs or mess arguments and still have a question why their database config is SQLite > or why my API starter kit is using Session guard ?
From what I've seen, default settings are supposed to work for most people, but that doesn't seem to fit here. Not everyone's going to need SQLite or Sessions for every project, right? So, why not throw in a simple prompt to let people pick what suits them. pretty easy and straightforward.

and, if we really decide to use configuration files from 3rd party kits in the nearly future, they shuold easily adapt to use this prompt by changing just a few lines of code.

**Comment by thetutlage** [comment]
I think, we have some expectations mismatch here. So, instead of look at the technicals, let's talk about what we expect from the `create-adonisjs` CLI.

Lemme speak for myself.

- First, I am personally not a big fan of too many prompts. Just use the CLI flags and create the project you want. Here personal workflow of aliases can help too. Do you always create a new app with `postgresql`. Then create an alias for that.
- Second, I do not want package configure hook or `create-adonisjs` CLI to be super complex. In v5, these tools were complex and I hated maintaining them. Because, everyone once in a while, someone will ask to add one more prompt, one more customization and then you end up with 30 combinations in total applying all different customizations.

Again, this is my thought process on it. If we decide to go with over customization, then we might have to do some major refactors, because the tool in its current state is not ready to run `configure.ts` file from starter kits and properly display logs + prompts in the minimal tasks CLI UI we have got.

**Comment by thetutlage** [comment]
> Think of it like this: someone could just run npm init adonisjs and boom. they're on their way without having to dig through a ton of docs or mess arguments

Maybe I am nitpicking, so please do not take it personal. I just want to clarify my stand as the creator of the framework :)

I do not want anyone to skip docs and try to build their first app. They will be lost and will consider every roadblock as a bug or frustration. Either you start with a tutorial, or spend some time on docs to understand pieces of the framework.

**Comment by n0uur** [comment]
First, I totally agree with you on the point about skipping docs, which I think happens a lot with beginners, It's make a lot of pain to me when trying to teach someone into programming 😢 
Secondly, I really appreciate your work on this framework. I love it and want to support it any way I can.

I'm just trying to make the setup more user-friendly from the perspective of someone who's been using Adonis even if I'm using it just only for a few years.

Regarding the concern about "too many prompts," I believe it won't be an issue because the CLI arguments are still there for setting up the `db` and `guard`. The prompts only show if no options are specified through the arguments, so there's no disruption for users who prefer to use CLI and arguments. the only case that this prompt will bother you is you want to use `session` and `SQLite` from the default options.

Thanks!

PS. I totally respect whatever decision you make. it's your call, no hard feelings at all. 😄

**Comment by n0uur** [comment]
I just realized about the prompt conditions in descriptions wasn't clear enough, and I'm really sorry if it caused any confusion.

**Comment by thetutlage** [comment]
Let's merge this PR and we will later handle the case in which we want starter kits to have `configure.ts` file to configure themselves.

**Comment by thetutlage** [comment]
Thanks @n0uur for taking out the time to create the PR and engage in the discussion :)

**Pull request merged**
